### ISSUE TITLE
Feed not updating 

### ISSUE THREAD

**Issue by aperturedata** [tentwentyfour/ge-rss-reader#1]
Can I ask what reason would the rss feed not update I really like ur plugin but or our intranet its not updating unless users hit it

**Comment by kwisatz** [comment]
Thanks for your appreciation.

The plugin does not use any cron functionality. Feeds are indeed only retrieved when users load a page.  The retrieved data is then cached for a certain amount of time (12 hours by default) before we attempt to retrieve it again.
If your sources change more often than that, you could use the [wp_feed_cache_transient_lifetime](https://codex.wordpress.org/Plugin_API/Filter_Reference/wp_feed_cache_transient_lifetime) WordPress filter (e.g. in your theme's functions.php) to set this to a lower value.

**Comment by aperturedata** [comment]
Yes thank you its a great we plugin I found that just before you  said it so again thanks
